INSERT INTO books (book_name, published_amount, sold_amount) VALUES ('Harry Potter', 2022123, 21314234),
                                                                    ('House of dragon', 1123124, 23441232),
                                                                    ('Twilight', 12313123, 34234),
                                                                    ('Girl with the Dragon Tattoo,The:Millennium Trilogy', 12312334, 5564567),
                                                                    ('Fifty Shades Freed', 24567545, 65736545),
                                                                    ('New Moon', 3453434, 433452),
                                                                    ('Deception Point', 134566,786745),
                                                                    ('Eclipse', 4544647, 5746734),
                                                                    ('Lovely Bones', 562453, 3456546),
                                                                    ('Curious Incident of the Dog in the Night-time', 3745674, 5678578),
                                                                    ('Digital Fortress', 245546, 45635653),
                                                                    ('Short History of Nearly Everything', 5635636, 34563456),
                                                                    ('Breaking Dawn', 2435456 ,4745434),
                                                                    ('Gruffalo', 6573673, 567456),
                                                                    ('One Day',3425234,36354);

INSERT INTO authors(author_name, birth_date, phone, email) VALUES ('Stephen King', '1947-09-21', '4686687978', 'king@gmail.com'),
                                                                  ('J. K. Rowling', '1965-07-31', '5384855043', 'J.R.@gmail.com'),
                                                                  ('Agatha Christie', '1890-09-15', '5635643323', 'Agatha@gmail.com'),
                                                                  ('John Grisham', '1955-02-08', '653453323', 'Jhon@gmail.com'),
                                                                  ('Lev Tolstoy', '1828-09-09', '56234235', 'Lev@gmail.com'),
                                                                  ('James Patterson', '1947-05-22', '6324246', 'Patterson@gmail.com'),
                                                                  ('William Shakespeare', '1564-04-26', '53566424', 'william@gmail.com'),
                                                                  ('Dr. Seuss', '1904-05-02', '3563425467', 'doc@gmail.com') ;

INSERT INTO  books_authors(book_id, author_id) VALUES (1,2),
                                                     (1,1),
                                                     (1,3),
                                                     (2,2),
                                                     (2,3),
                                                     (2,4),
                                                     (3,5),
                                                     (3,6),
                                                     (4,2),
                                                     (4,1),
                                                     (4,4),
                                                     (5,4),
                                                     (5,5),
                                                     (5,7),
                                                     (5,8),
                                                     (5,3),
                                                     (6,3),
                                                     (6,5),
                                                     (6,7),
                                                     (6,1),
                                                     (7,6),
                                                     (7,3),
                                                     (7,5),
                                                     (7,8),
                                                     (8,8),
                                                     (8,2),
                                                     (8,6),
                                                     (9,3),
                                                     (9,2),
                                                     (9,5),
                                                     (10,1),
                                                     (10,4),
                                                     (11,2),
                                                     (12,7),
                                                     (13,7),
                                                     (14,8),
                                                     (14,6),
                                                     (15,5),
                                                     (15,8);